apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: alissonbrisa123/dbappkubernetes:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: alissonbrisa123/php:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

